name: Grammar Check

on:
  workflow_dispatch:
  repository_dispatch:
    types: [grammar-check]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Show payload
        run: |
          echo "Event:  ${{ github.event_name }}"
          echo "Type:   ${{ github.event.action || github.event.client_payload.audit_type }}"
          echo "Client: ${{ github.event.client_payload.client_id }}"
          echo "URL:    ${{ github.event.client_payload.url }}"
