name: Grammar Check

on:
  workflow_dispatch:
  repository_dispatch:
    types: [grammar-check]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID:        ${{ github.event.client_payload.client_id }}
      AUDIT_TYPE:       ${{ github.event.client_payload.audit_type }}
      TARGET_URL:       ${{ github.event.client_payload.url }}
      OPENAI_API_KEY:   ${{ secrets.OPENAI_API_KEY }}   # optional; only used if you enabled OpenAI
      CALLBACK_URL:     ${{ secrets.CALLBACK_URL }}     # <-- add this secret
      CALLBACK_KEY:     ${{ secrets.CALLBACK_KEY }}     # <-- add this secret
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run checker
        run: node scripts/grammar-check.js

      - name: Upload results (optional)
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}
          path: out/results.json

      - name: Send results to Google Doc
        if: ${{ env.CALLBACK_URL != '' }}
        run: |
          curl -sS -L --post301 --post302 --fail-with-body \
            -X POST "$CALLBACK_URL" \
            -H "Content-Type: application/json" \
            -H "x-api-key: $CALLBACK_KEY" \
            --data-binary @out/results.json

