# .github/workflows/grammar-check.yml
name: Grammar Check
on:
  repository_dispatch:
    types: [grammar-check]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Extract pushed text to doc.txt
        run: |
          jq -r '.client_payload.text // empty' "$GITHUB_EVENT_PATH" > doc.txt
          if [ ! -s doc.txt ]; then
            echo "No text found in client_payload.text"
            echo "Payload was:"; cat "$GITHUB_EVENT_PATH"
            exit 1
          fi
          # Guard: fail fast if we accidentally got an HTML error page
          if head -c 20 doc.txt | grep -qi '<html'; then
            echo "Received HTML instead of text, aborting."; exit 1
          fi
          echo "Wrote $(wc -c < doc.txt) bytes to doc.txt"

      # 👉 run your grammar checker against doc.txt here
      - name: Run grammar check
        run: |
          ./scripts/run_grammar_check.sh doc.txt
