name: Grammar Check
on:
  workflow_dispatch:
  repository_dispatch:
    types: [grammar-check]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CLIENT_ID:  ${{ github.event.client_payload.client_id }}
      AUDIT_TYPE: ${{ github.event.client_payload.audit_type }}
      TARGET_URL: ${{ github.event.client_payload.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run checker
        run: |
          node scripts/grammar-check.js
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ github.run_id }}
          path: out/results.json
